name: CI/CD Pipeline

permissions:
  contents: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Get latest Emscripten version
      id: emsdk-version
      run: |
        echo "emsdk_version=$(wget -O- -q https://raw.githubusercontent.com/emscripten-core/emscripten/main/emscripten-version.txt)" >> $GITHUB_ENV

    - name: Cache Emscripten
      uses: actions/cache@v3
      with:
        path: |
          **/emsdk
        key: ${{ runner.os }}-emsdk-${{ env.emsdk_version }}
        restore-keys: |
          ${{ runner.os }}-emsdk-
          
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install npm dependencies
      run: |
        if [ ! -d "node_modules" ]; then
          npm ci
        fi
        
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13

    - name: Install Emscripten
      run: |
        if [ ! -d "emsdk" ]; then
          git clone --depth=1 https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
        fi
      
    - name: Build
      run: |
        source emsdk/emsdk_env.sh
        npm run wasm-build
        NODE_ENV=production npm run generate

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .output/public
